defaults:

  seed: 0
  dataset: ''


  jax:
    gpus: [0,]


  run:
    steps: 10000
    eval_every: 100

  data_shape: [28, 28]
  latent_dim: 4

  gen_hidden: [128, 256]
  rec_hidden: [512, 256, 128, 64]
  act: relu
  init: {init: glorot_normal, params: None}
  opt: {opt: adam, lr: 1e-3}



mnist:
  init: {init: normal, params: [0.0, 0.01]}
  opt: {opt: adagrad, lr: 1e-1}


small:
  {gen_hidden: [128, 784], rec_hidden: [128, 64]}