[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"



[project]
name = "aevb"
authors= [{name = "Paul Scemama", email = "ptscemama@gmail.com"}]
dynamic = ["version"]

[tool.setuptools]
packages = ["aevb"]
platforms = [
    "Linux",
]

